name: Backend CI (Python + SAM)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Debug: print tree so we can see actual paths in the runner
      - name: Debug repo tree
        run: |
          pwd
          ls -la
          echo "---- level 1 ----"
          ls -la cloud-resume-challenge || true
          echo "---- level 2 ----"
          ls -la cloud-resume-challenge/cloud-resume-challenge || true
          echo "---- find template.yaml ----"
          find . -name template.yaml -maxdepth 4 -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dev dependencies (inner folder path)
        run: |
          python -m pip install --upgrade pip
          pip install -r cloud-resume-challenge/cloud-resume-challenge/requirements-dev.txt

      # OK if you haven't written real tests yet
      - name: Run tests (tolerate no tests yet)
        run: |
          PYTHONPATH=cloud-resume-challenge/cloud-resume-challenge/get-function:cloud-resume-challenge/cloud-resume-challenge/put-function \
          pytest -q cloud-resume-challenge/cloud-resume-challenge/tests || true

      - name: Install SAM CLI
        run: |
          python -m pip install --upgrade pipx
          pipx ensurepath
          pipx install aws-sam-cli
          sam --version
        shell: bash

      - name: Validate SAM (point to inner template.yaml)
        run: sam validate -t cloud-resume-challenge/cloud-resume-challenge/template.yaml

      - name: Build SAM (point to inner template.yaml)
        run: sam build -t cloud-resume-challenge/cloud-resume-challenge/template.yaml
